### PR TITLE
Add `@overload` to `Connection.send()`

### PR DESCRIPTION
**Pull request by Kludex**
I need this to not cast a lot of stuff on uvicorn. 🙏

### CODE REVIEW

**Comment by Kludex** [comment]
This pipeline fails because the format tooling (black) is not pinned.

**Comment by madkinsz** [comment]
> This pipeline fails because the format tooling (black) is not pinned.

https://github.com/python-hyper/h11/pull/162

**Comment by sethmlarson** [comment]
Can rebase this PR now.

**Comment by Kludex** [comment]
> Can rebase this PR now.

Done! 🙏

**Comment by Kludex** [comment]
👋 👀

**Review by sethmlarson — APPROVED** [review]

**Comment by Kludex** [comment]
Thanks @sethmlarson 🙏

**Pull request merged**
